language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"
notifications:
slack:
  rooms:
    - getvenueapp:SihQje8RJE8WgLGyOgcL1iSP#travis